# Arquivo de configuração "Blueprint" para o deploy na Render.com
# Este arquivo deve ser criado na raiz do seu projeto.

# 1. Definição do Banco de Dados
databases:
  - name: anfitriao-pro-db
    databaseName: anfitriao_pro_db
    user: anfitriao_pro_user
    plan: free
    region: ohio

# 2. Definição dos Serviços
services:
  # Serviço Web (sua aplicação Laravel)
  - type: web
    name: anfitriao-pro
    # CORREÇÃO: A chave correta para um projeto Laravel é 'env: laravel'.
    # Isso instrui a Render a usar seu ambiente otimizado para Laravel.
    env: laravel
    plan: free
    region: ohio

    # Comandos para construir o projeto a cada novo deploy
    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force

    # Comando para iniciar o servidor web
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    # Definição das Variáveis de Ambiente
    envVars:
      - key: APP_NAME
        value: "Anfitrião Pro"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: anfitriao-pro-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: anfitriao-pro-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: anfitriao-pro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: anfitriao-pro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: anfitriao-pro-db
          property: password
